name: nirdesa
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  translator: ^0.1.7
  audioplayers: ^1.1.1
  http: ^0.13.5
  google_fonts: ^3.0.1
  localstorage: ^4.0.0+1
  search_page: ^2.2.0
  searchbar_animation: ^0.0.4
  scroll_to_index: ^3.0.1
  animated_size_and_fade: ^3.0.1
  scroll_to_id: ^1.5.1
  url_strategy: ^0.2.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

